name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

 trivy_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: [actions/checkout@v4](https://github.com)

    - name: Run Trivy vulnerability scanner on an image
      uses: [aquasecurity/trivy-action@master](https://github.com/aquasecurity/trivy-action)
      with:
        image-ref: 'ruby:2.4.0'
        exit-code: '0'
        severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
        format: 'table'

