name: Build and Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker Image
      run: |
        docker build -t my-python-app:${{ github.sha }} .

    - name: Run Trivy vulnerability scanner (Report)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'my-python-app:${{ github.sha }}'
        format: 'table'
        exit-code: '0' 
        severity: 'CRITICAL,HIGH'

    
    - name: Run Trivy Security Gate
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'my-python-app:${{ github.sha }}'
        format: 'table'
        exit-code: '1' 
        ignore-unfixed: true
        severity: 'CRITICAL'